# ------ Traer todos los productos ------ 
/api/carrito:
  post:
    tags: [Carts]
    summary: Crear carrito
    responses:
      '200':
        description: Se creó un carrito
        content:
          application/json:
            schema:
              type: object
              example: '{message:`carrito creado}'
      '500':
        description: No se pudo crear el carrito
        content:
          application/json:
            schema:
              type: object
            example: "{message:'No se pudo crear el carrito'}"
/api/carrito/{id}:
  delete:
    tags: [Carts]
    summary: Elimina un carrito por su Id
    parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del carrito a eliminar
    responses:
      '200':
        description: Carrito eliminado
        content:
          application/json:
            schema:
              type: object
            example: "{message:`Se borró el carrito con el id: ${id}.`}"
      '404':
        description: El carrito no se pudo eliminar, porque ya no existía
        content:
          application/json:
            schema:
              type: object
            example: "{mensaje:`No se puede borrar carrito con id: ${id}, porque no existe`}"

/api/carrito/{id}/productos:
  get:
    tags: [Carts]
    summary: Trae el array de productos del carrito
    parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del carrito que se necesita traer los productos
    responses:
      '200':
        description: Productos del carrito
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Product'
      '404':
        description: El carrito no existe
        content:
          application/json:
            schema:
              type: object
            example: "{message:`El carrito con el id número: ${idCart}, no existe`}"
  post:
    tags: [Carts]
    summary: Añade un producto al carrito
    parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del carrito
          example: 62e5b435812232251965fd0c
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                description: id del producto
                example: 62cddf78539feda573da0f62
    responses:
      '200':
        description: Productos del carrito
        content:
          application/json:
            schema:
              type: object
              items: "{message:`Se añadió el producto con id ${idProduct} al carrito con el id ${idCart}`}"
      '404':
        description: El carrito no existe
        content:
          application/json:
            schema:
              type: object
            example: "{error:`El carrito con el id número: ${idCart}, no existe, y/o el producto con el id número: ${idProduct}, no existe`}"
  delete:
    tags: [Carts]
    summary: Elimina un producto del carrito
    parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del carrito
          example: 62e5b435812232251965fd0c
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                description: id del producto
                example: 62cddf78539feda573da0f62
    responses:
      '200':
        description: Se elimino el producto del carrito
        content:
          application/json:
            schema:
              type: object
            example: "{message:`Se eliminó el producto con id ${idProduct} del carrito con el id ${idCart}`}"
      '404':
        description: El carrito no existe
        content:
          application/json:
            schema:
              type: object
            example: "{error:`El carrito con el id número: ${idCart}, no existe, y/o el producto con el id número: ${idProduct}, no existe`}"
    